definitions:
  models.Empresa:
    description: Representa uma empresa cadastrada no sistema
    properties:
      area_de_atuacao:
        type: string
      ativo:
        type: boolean
      bairro:
        type: string
      cidade:
        type: string
      cnpj:
        type: string
      data_cadastro:
        type: string
      descricao:
        type: string
      email:
        type: string
      logradouro:
        type: string
      nome_fantasia:
        type: string
      numero:
        type: string
      razao_social:
        type: string
      telefone:
        type: string
      uf:
        type: string
      website:
        type: string
    type: object
  models.Usuario:
    description: Representa um usuário do sistema
    properties:
      ativo:
        type: boolean
      data_cadastro:
        type: string
      email:
        type: string
      empresa_cnpj:
        description: Chave estrangeira opcional
        type: string
      id:
        type: integer
      nome:
        type: string
      senha:
        type: string
      tipo_usuario:
        description: true = ADMIN, false = EMPRESA
        type: boolean
    type: object
  models.Vaga:
    description: Representa uma vaga de emprego ou estágio no sistema
    properties:
      ativo:
        type: boolean
      bairro:
        type: string
      beneficios:
        type: string
      carga_horaria:
        type: string
      cidade:
        type: string
      conhecimento_dif:
        type: string
      data_expiracao:
        type: string
      data_publicacao:
        type: string
      descricao:
        type: string
      empresa_cnpj:
        description: Chave estrangeira para Empresa
        type: string
      estagio_remoto:
        description: 0 = Presencial, 1 = Remoto, 2 = Híbrido
        type: integer
      id:
        type: integer
      logradouro:
        type: string
      numero:
        type: string
      remuneracao:
        type: string
      requisitos:
        type: string
      titulo:
        type: string
      uf:
        type: string
    type: object
info:
  contact: {}
paths:
  /empresas:
    get:
      consumes:
      - application/json
      description: Retorna uma lista de todas as empresas cadastradas no sistema
      produces:
      - application/json
      responses:
        "200":
          description: Lista de empresas
          schema:
            items:
              $ref: '#/definitions/models.Empresa'
            type: array
        "201":
          description: Nenhuma empresa cadastrada
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro ao listar empresas
          schema:
            additionalProperties: true
            type: object
      summary: Lista todas as empresas
      tags:
      - Empresas
    post:
      consumes:
      - application/json
      description: Cadastra uma nova empresa no sistema
      parameters:
      - description: Dados da empresa
        in: body
        name: empresa
        required: true
        schema:
          $ref: '#/definitions/models.Empresa'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Empresa'
        "400":
          description: Falha ao cadastrar empresa
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro ao salvar empresa no banco de dados
          schema:
            additionalProperties: true
            type: object
      summary: Cria uma nova empresa
      tags:
      - Empresas
  /empresas/{cnpj}:
    delete:
      consumes:
      - application/json
      description: Exclui uma empresa do sistema pelo CNPJ
      parameters:
      - description: CNPJ da empresa
        in: path
        name: cnpj
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Empresa excluída com sucesso
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Empresa não encontrada
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro ao deletar a empresa
          schema:
            additionalProperties: true
            type: object
      summary: Deleta uma empresa
      tags:
      - Empresas
    get:
      consumes:
      - application/json
      description: Busca uma empresa pelo CNPJ informado
      parameters:
      - description: CNPJ da empresa
        in: path
        name: cnpj
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Empresa'
        "404":
          description: Empresa não encontrada
          schema:
            additionalProperties: true
            type: object
      summary: Exibe uma empresa pelo CNPJ
      tags:
      - Empresas
    put:
      consumes:
      - application/json
      description: Atualiza as informações de uma empresa no sistema
      parameters:
      - description: CNPJ da empresa
        in: path
        name: cnpj
        required: true
        type: string
      - description: Dados atualizados da empresa
        in: body
        name: empresa
        required: true
        schema:
          $ref: '#/definitions/models.Empresa'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Empresa'
        "400":
          description: Falha ao processar os dados da empresa
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Empresa não encontrada
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro ao atualizar a empresa
          schema:
            additionalProperties: true
            type: object
      summary: Altera os dados de uma empresa existente
      tags:
      - Empresas
  /empresas/nome/{nome}:
    get:
      consumes:
      - application/json
      description: Retorna os dados de uma empresa com base no nome
      parameters:
      - description: Nome da empresa
        in: path
        name: nome
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Empresa'
        "404":
          description: Empresa não encontrada
          schema:
            additionalProperties: true
            type: object
      summary: Exibe informações de uma empresa pelo nome
      tags:
      - Empresas
  /usuarios:
    get:
      consumes:
      - application/json
      description: Retorna uma lista de todos os usuários cadastrados no sistema
      produces:
      - application/json
      responses:
        "200":
          description: Lista de usuários
          schema:
            items:
              $ref: '#/definitions/models.Usuario'
            type: array
        "201":
          description: Nenhum usuário cadastrado
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro ao listar usuários
          schema:
            additionalProperties: true
            type: object
      summary: Lista todos os usuários
      tags:
      - Usuários
    post:
      consumes:
      - application/json
      description: Cadastra um novo usuário no sistema
      parameters:
      - description: Dados do usuário
        in: body
        name: usuario
        required: true
        schema:
          $ref: '#/definitions/models.Usuario'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Usuario'
        "400":
          description: Falha ao cadastrar usuário
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro ao salvar usuário no banco de dados
          schema:
            additionalProperties: true
            type: object
      summary: Cria um novo usuário
      tags:
      - Usuários
  /usuarios/{email}:
    get:
      consumes:
      - application/json
      description: Busca um usuário pelo e-mail informado
      parameters:
      - description: E-mail do usuário
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Usuario'
        "404":
          description: Usuário não encontrado
          schema:
            additionalProperties: true
            type: object
      summary: Exibe um usuário pelo e-mail
      tags:
      - Usuários
  /usuarios/{id}:
    delete:
      consumes:
      - application/json
      description: Remove um usuário do sistema pelo ID
      parameters:
      - description: ID do usuário
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Usuário deletado com sucesso
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Usuário não encontrado
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro ao deletar o usuário
          schema:
            additionalProperties: true
            type: object
      summary: Deleta um usuário
      tags:
      - Usuários
    put:
      consumes:
      - application/json
      description: Atualiza os dados de um usuário existente pelo ID
      parameters:
      - description: ID do usuário
        in: path
        name: id
        required: true
        type: integer
      - description: Novos dados do usuário
        in: body
        name: usuario
        required: true
        schema:
          $ref: '#/definitions/models.Usuario'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Usuario'
        "400":
          description: Dados inválidos para atualização
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Usuário não encontrado
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro ao atualizar o usuário
          schema:
            additionalProperties: true
            type: object
      summary: Atualiza os dados de um usuário
      tags:
      - Usuários
  /vagas:
    get:
      consumes:
      - application/json
      description: Retorna uma lista de todas as vagas cadastradas no sistema
      produces:
      - application/json
      responses:
        "200":
          description: Lista de vagas
          schema:
            items:
              $ref: '#/definitions/models.Vaga'
            type: array
        "500":
          description: Erro ao listar vagas
          schema:
            additionalProperties: true
            type: object
      summary: Lista todas as vagas
      tags:
      - Vagas
    post:
      consumes:
      - application/json
      description: Cadastra uma nova vaga no sistema
      parameters:
      - description: Dados da vaga
        in: body
        name: vaga
        required: true
        schema:
          $ref: '#/definitions/models.Vaga'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Vaga'
        "400":
          description: Falha ao cadastrar vaga
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro ao salvar vaga no banco de dados
          schema:
            additionalProperties: true
            type: object
      summary: Cria uma nova vaga
      tags:
      - Vagas
  /vagas/{id}:
    delete:
      consumes:
      - application/json
      description: Remove uma vaga do sistema pelo ID
      parameters:
      - description: ID da vaga
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Vaga deletada com sucesso
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Vaga não encontrada
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro ao deletar a vaga
          schema:
            additionalProperties: true
            type: object
      summary: Deleta uma vaga
      tags:
      - Vagas
    get:
      consumes:
      - application/json
      description: Busca uma vaga pelo ID informado
      parameters:
      - description: ID da vaga
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Vaga'
        "404":
          description: Vaga não encontrada
          schema:
            additionalProperties: true
            type: object
      summary: Exibe uma vaga pelo ID
      tags:
      - Vagas
    put:
      consumes:
      - application/json
      description: Atualiza os dados de uma vaga existente pelo ID
      parameters:
      - description: ID da vaga
        in: path
        name: id
        required: true
        type: integer
      - description: Novos dados da vaga
        in: body
        name: vaga
        required: true
        schema:
          $ref: '#/definitions/models.Vaga'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Vaga'
        "400":
          description: Dados inválidos para atualização
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Vaga não encontrada
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro ao atualizar a vaga
          schema:
            additionalProperties: true
            type: object
      summary: Atualiza os dados de uma vaga
      tags:
      - Vagas
  /vagas/cnpj/{cnpj}:
    get:
      consumes:
      - application/json
      description: Retorna uma lista de todas as vagas associadas ao CNPJ da empresa
      parameters:
      - description: CNPJ da empresa
        in: path
        name: cnpj
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Lista de vagas associadas ao CNPJ
          schema:
            items:
              $ref: '#/definitions/models.Vaga'
            type: array
        "404":
          description: Nenhuma vaga encontrada para o CNPJ
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro ao listar vagas
          schema:
            additionalProperties: true
            type: object
      summary: Lista todas as vagas associadas a um CNPJ
      tags:
      - Vagas
swagger: "2.0"
